### ISSUE TITLE
PickerManager.java line 203 | java.lang.RuntimeException: An error occured while executing doInBackground()

### ISSUE THREAD

**Issue by zeevy** [zeevy/grblcontroller#87]
Device
Brand: Sony
Model: Xperia Z
Orientation: Portrait
RAM free: 505.64 MB
Disk free: 3.59 GB 

Operating System
Version: 5.1.1
Orientation: Portrait
Rooted: Yes 

Crash
Date: Sep 16, 2018, 3:36:00 PM
App version: 2.32 (23) 

```
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

Caused by java.lang.NullPointerException: Attempt to read from field 'java.util.LinkedHashMap$LinkedEntry java.util.LinkedHashMap$LinkedEntry.nxt' on a null object reference
       at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:350)
       at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:366)
       at java.util.AbstractCollection.toArrayList(AbstractCollection.java:349)
       at java.util.AbstractCollection.toArray(AbstractCollection.java:339)
       at java.util.ArrayList.<init>(ArrayList.java:97)
       at droidninja.filepicker.PickerManager.getFileTypes(PickerManager.java:203)
       at droidninja.filepicker.cursors.DocScannerTask.getDocumentFromCursor(DocScannerTask.java:112)
       at droidninja.filepicker.cursors.DocScannerTask.doInBackground(DocScannerTask.java:89)
       at droidninja.filepicker.cursors.DocScannerTask.doInBackground(DocScannerTask.java:32)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

```

**Comment by zeevy** [comment]
Dependent lib was no longer used in recent versions
