### ISSUE TITLE
RuntimeException: WakeLock under-locked | FileStreamerIntentService.java line 193

### ISSUE THREAD

**Issue by zeevy** [zeevy/grblcontroller#96]
### Disk Free: 85.9%

```
#0. Crashed: IntentService[in.co.gorest.grblcontroller.service.FileStreamerIntentService]
       at android.os.PowerManager$WakeLock.release(PowerManager.java:1058)
       at android.os.PowerManager$WakeLock.release(PowerManager.java:1029)
       at in.co.gorest.grblcontroller.service.FileStreamerIntentService.onHandleIntent(FileStreamerIntentService.java:193)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.os.HandlerThread.run(HandlerThread.java:61)

--

Non-fatal Exception: java.lang.RuntimeException: WakeLock under-locked Grbl File Streaming
       at android.os.PowerManager$WakeLock.release(PowerManager.java:1058)
       at android.os.PowerManager$WakeLock.release(PowerManager.java:1029)
       at in.co.gorest.grblcontroller.service.FileStreamerIntentService.onHandleIntent(FileStreamerIntentService.java:193)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.os.HandlerThread.run(HandlerThread.java:61)

#0. Crashed: IntentService[in.co.gorest.grblcontroller.service.FileStreamerIntentService]
       at android.os.PowerManager$WakeLock.release(PowerManager.java:1058)
       at android.os.PowerManager$WakeLock.release(PowerManager.java:1029)
       at in.co.gorest.grblcontroller.service.FileStreamerIntentService.onHandleIntent(FileStreamerIntentService.java:193)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by zeevy** [comment]
fixed in recent version
